import type { Unit } from "./work-units";

const joinRoles: Unit["roles"] = ["developer", "product-owner", "manager"];
const leadRoles: Unit["roles"] = ["tech-lead", "scrum-master"];

export const extraDailyUnits: Unit[] = [
  {
    id: "daily-dev-2",
    title: "Daily 2",
    blurb: "PR, teste e espera de design.",
    track: "work",
    scene: "daily",
    journey: 2,
    roles: joinRoles,
    speak: [
      { en: "Yesterday I opened the pull request.", pt: "Ontem eu abri o pull request." },
      { en: "Today I will write the tests.", pt: "Hoje vou escrever os testes." },
      { en: "I am waiting on the design.", pt: "Estou esperando o design." },
      { en: "I can pair with you after the daily.", pt: "Posso fazer pair com você depois da daily." },
      { en: "No blockers on my side.", pt: "Sem impedimentos do meu lado." },
      { en: "I should finish this today.", pt: "Devo terminar isso hoje." },
    ],
    write: [
      {
        prompt: "Diga que ontem você abriu o pull request.",
        hint: "Yesterday I opened ...",
        answers: ["yesterday i opened the pull request", "yesterday i opened the pr"],
        tip: "Opened = abri. Pull request = PR.",
      },
      {
        prompt: "Diga que hoje você vai escrever os testes.",
        hint: "Today I will write ...",
        answers: ["today i will write the tests", "today i'll write the tests"],
        tip: "Write the tests = escrever os testes.",
      },
      {
        prompt: "Diga que está esperando o design.",
        hint: "I am waiting on ...",
        answers: ["i am waiting on the design", "i'm waiting on the design", "i am waiting for the design"],
        tip: "Waiting on = esperando (alguém / algo).",
      },
      {
        prompt: "Diga que não tem impedimentos do seu lado.",
        hint: "No blockers ...",
        answers: ["no blockers on my side", "i have no blockers on my side"],
        tip: "On my side = do meu lado.",
      },
    ],
  },
  {
    id: "daily-dev-3",
    title: "Daily 3",
    blurb: "Bug, reunião e pedir ajuda.",
    track: "work",
    scene: "daily",
    journey: 3,
    roles: joinRoles,
    speak: [
      { en: "Yesterday I fixed a bug in checkout.", pt: "Ontem eu corrigi um bug no checkout." },
      { en: "Today I have a meeting with the client.", pt: "Hoje tenho reunião com o cliente." },
      { en: "I am blocked by the API timeout.", pt: "Estou bloqueado pelo timeout da API." },
      { en: "Can someone review my pull request?", pt: "Alguém pode revisar o meu pull request?" },
      { en: "I will continue after lunch.", pt: "Vou continuar depois do almoço." },
      { en: "I need 30 more minutes.", pt: "Preciso de mais 30 minutos." },
    ],
    write: [
      {
        prompt: "Diga que ontem você corrigiu um bug no checkout.",
        hint: "Yesterday I fixed ...",
        answers: ["yesterday i fixed a bug in checkout", "yesterday i fixed a bug in the checkout"],
        tip: "Fixed a bug = corrigi um bug.",
      },
      {
        prompt: "Diga que hoje tem reunião com o cliente.",
        hint: "Today I have a meeting ...",
        answers: ["today i have a meeting with the client", "today i have a client meeting"],
        tip: "Meeting with the client = reunião com o cliente.",
      },
      {
        prompt: "Peça para alguém revisar o seu PR.",
        hint: "Can someone review ...",
        answers: ["can someone review my pull request", "can someone review my pr"],
        tip: "Review my pull request = revisar o meu PR.",
      },
      {
        prompt: "Diga que precisa de mais 30 minutos.",
        hint: "I need 30 ...",
        answers: ["i need 30 more minutes", "i need 30 minutes more", "i need another 30 minutes"],
        tip: "More minutes = mais minutos.",
      },
    ],
  },
  {
    id: "daily-dev-4",
    title: "Daily 4",
    blurb: "Deploy, incidente e ETA.",
    track: "work",
    scene: "daily",
    journey: 4,
    roles: joinRoles,
    speak: [
      { en: "Yesterday I deployed to staging.", pt: "Ontem eu fiz deploy no staging." },
      { en: "Today I will watch production.", pt: "Hoje vou acompanhar a produção." },
      { en: "We had a small incident this morning.", pt: "Tivemos um incidente pequeno esta manhã." },
      { en: "It is stable now.", pt: "Agora está estável." },
      { en: "I will share the notes in Slack.", pt: "Vou compartilhar as notas no Slack." },
      { en: "ETA is one hour.", pt: "O prazo estimado é uma hora." },
    ],
    write: [
      {
        prompt: "Diga que ontem você fez deploy no staging.",
        hint: "Yesterday I deployed ...",
        answers: ["yesterday i deployed to staging", "yesterday i deployed on staging"],
        tip: "Deployed to staging = fiz deploy no staging.",
      },
      {
        prompt: "Avise que houve um incidente pequeno esta manhã.",
        hint: "We had a small incident ...",
        answers: ["we had a small incident this morning", "we had a small incident this morning."],
        tip: "Incident = incidente. This morning = esta manhã.",
      },
      {
        prompt: "Diga que agora está estável.",
        hint: "It is stable ...",
        answers: ["it is stable now", "it's stable now", "it is stable now."],
        tip: "Stable = estável.",
      },
      {
        prompt: "Diga que o ETA é uma hora.",
        hint: "ETA is ...",
        answers: ["eta is one hour", "the eta is one hour", "eta is 1 hour"],
        tip: "ETA = prazo estimado.",
      },
    ],
  },
  {
    id: "daily-dev-5",
    title: "Daily 5",
    blurb: "Ajudar o time e fechar a história.",
    track: "work",
    scene: "daily",
    journey: 5,
    roles: joinRoles,
    speak: [
      { en: "Yesterday I helped a teammate.", pt: "Ontem eu ajudei um colega." },
      { en: "Today I will close this story.", pt: "Hoje vou fechar esta história." },
      { en: "I have no blockers.", pt: "Não tenho impedimentos." },
      { en: "I can take one more task if needed.", pt: "Posso pegar mais uma tarefa se precisar." },
      { en: "Let's sync after the daily.", pt: "Vamos alinhar depois da daily." },
      { en: "I am free this afternoon.", pt: "Estou livre nesta tarde." },
    ],
    write: [
      {
        prompt: "Diga que ontem você ajudou um colega.",
        hint: "Yesterday I helped ...",
        answers: ["yesterday i helped a teammate", "yesterday i helped a colleague"],
        tip: "Teammate = colega de time.",
      },
      {
        prompt: "Diga que hoje vai fechar esta história.",
        hint: "Today I will close ...",
        answers: ["today i will close this story", "today i'll close this story"],
        tip: "Close this story = fechar esta história.",
      },
      {
        prompt: "Ofereça pegar mais uma tarefa se precisar.",
        hint: "I can take one more ...",
        answers: ["i can take one more task if needed", "i can take another task if needed"],
        tip: "If needed = se precisar.",
      },
      {
        prompt: "Diga que está livre nesta tarde.",
        hint: "I am free ...",
        answers: ["i am free this afternoon", "i'm free this afternoon"],
        tip: "Free = livre. This afternoon = nesta tarde.",
      },
    ],
  },
  {
    id: "daily-facilitate-2",
    title: "Daily 2",
    blurb: "Atraso, parking lot e timebox.",
    track: "work",
    scene: "daily",
    journey: 2,
    roles: leadRoles,
    speak: [
      { en: "We are starting two minutes late.", pt: "Estamos começando dois minutos atrasados." },
      { en: "Please keep updates to one minute.", pt: "Por favor, deixe o update em um minuto." },
      { en: "Let's put this in the parking lot.", pt: "Vamos deixar isso no parking lot." },
      { en: "Who is blocked today?", pt: "Quem está bloqueado hoje?" },
      { en: "We can follow up after this.", pt: "Podemos continuar isso depois." },
      { en: "Thanks, let's have a good day.", pt: "Obrigado, tenham um bom dia." },
    ],
    write: [
      {
        prompt: "Peça para o update ficar em um minuto.",
        hint: "Please keep updates ...",
        answers: ["please keep updates to one minute", "please keep the updates to one minute"],
        tip: "Keep updates to one minute = timebox do update.",
      },
      {
        prompt: "Sugira deixar o assunto no parking lot.",
        hint: "Let's put this in ...",
        answers: ["let's put this in the parking lot", "lets put this in the parking lot"],
        tip: "Parking lot = assunto para depois da daily.",
      },
      {
        prompt: "Pergunte quem está bloqueado hoje.",
        hint: "Who is blocked ...",
        answers: ["who is blocked today", "who is blocked today?"],
        tip: "Blocked = bloqueado / com impedimento.",
      },
      {
        prompt: "Diga que podem continuar isso depois.",
        hint: "We can follow up ...",
        answers: ["we can follow up after this", "we can follow up after the daily"],
        tip: "Follow up = continuar / tratar depois.",
      },
    ],
  },
  {
    id: "daily-facilitate-3",
    title: "Daily 3",
    blurb: "Foco, dois blockers e próximo passo.",
    track: "work",
    scene: "daily",
    journey: 3,
    roles: leadRoles,
    speak: [
      { en: "Let's focus on yesterday, today, and blockers.", pt: "Vamos focar em ontem, hoje e blockers." },
      { en: "Please go first.", pt: "Por favor, comece você." },
      { en: "I hear two people with the same blocker.", pt: "Ouço duas pessoas com o mesmo impedimento." },
      { en: "Can you two sync after the daily?", pt: "Vocês dois podem alinhar depois da daily?" },
      { en: "We are on time.", pt: "Estamos no horário." },
      { en: "Great, we are done.", pt: "Ótimo, terminamos." },
    ],
    write: [
      {
        prompt: "Peça para a pessoa começar.",
        hint: "Please go ...",
        answers: ["please go first", "please go first."],
        tip: "Go first = comece você.",
      },
      {
        prompt: "Peça para os dois alinharem depois da daily.",
        hint: "Can you two sync ...",
        answers: ["can you two sync after the daily", "can you both sync after the daily"],
        tip: "Sync = alinhar. After the daily = depois da daily.",
      },
      {
        prompt: "Diga que estão no horário.",
        hint: "We are on ...",
        answers: ["we are on time", "we're on time"],
        tip: "On time = no horário.",
      },
      {
        prompt: "Encerre a daily.",
        hint: "Great, we are ...",
        answers: ["great we are done", "great, we are done", "we are done"],
        tip: "We are done = terminamos.",
      },
    ],
  },
  {
    id: "daily-facilitate-4",
    title: "Daily 4",
    blurb: "Remoto, áudio e recado rápido.",
    track: "work",
    scene: "daily",
    journey: 4,
    roles: leadRoles,
    speak: [
      { en: "Can you unmute, please?", pt: "Pode ligar o microfone, por favor?" },
      { en: "We cannot hear you well.", pt: "Não estamos ouvindo bem." },
      { en: "Please use the chat if needed.", pt: "Use o chat se precisar." },
      { en: "Let's wait 10 seconds for people to join.", pt: "Vamos esperar 10 segundos para o pessoal entrar." },
      { en: "Quick reminder: update Jira after this.", pt: "Lembrete rápido: atualizem o Jira depois disso." },
      { en: "See you at the refinement.", pt: "Até o refinement." },
    ],
    write: [
      {
        prompt: "Peça para ligar o microfone.",
        hint: "Can you unmute ...",
        answers: ["can you unmute please", "can you unmute, please?"],
        tip: "Unmute = ligar o microfone.",
      },
      {
        prompt: "Diga que não estão ouvindo bem.",
        hint: "We cannot hear ...",
        answers: ["we cannot hear you well", "we can't hear you well"],
        tip: "Hear you well = ouvir bem.",
      },
      {
        prompt: "Peça para atualizar o Jira depois.",
        hint: "Quick reminder: update ...",
        answers: ["quick reminder update jira after this", "quick reminder: update jira after this"],
        tip: "Reminder = lembrete.",
      },
      {
        prompt: "Despeça-se até o refinement.",
        hint: "See you at ...",
        answers: ["see you at the refinement", "see you in the refinement"],
        tip: "See you at = até (o encontro).",
      },
    ],
  },
  {
    id: "daily-facilitate-5",
    title: "Daily 5",
    blurb: "Reconhecer o time e fechar com clareza.",
    track: "work",
    scene: "daily",
    journey: 5,
    roles: leadRoles,
    speak: [
      { en: "Nice progress on the login, team.", pt: "Bom progresso no login, time." },
      { en: "Does anyone need help after this?", pt: "Alguém precisa de ajuda depois disso?" },
      { en: "I will stay on the call if you want.", pt: "Eu fico na call se vocês quiserem." },
      { en: "Please be on time tomorrow.", pt: "Por favor, cheguem no horário amanhã." },
      { en: "Our next ceremony is planning.", pt: "Nossa próxima cerimônia é o planning." },
      { en: "Thanks everyone, have a good one.", pt: "Obrigado a todos, tenham um bom dia." },
    ],
    write: [
      {
        prompt: "Reconheça o progresso do time no login.",
        hint: "Nice progress on ...",
        answers: ["nice progress on the login team", "nice progress on the login, team"],
        tip: "Nice progress = bom progresso.",
      },
      {
        prompt: "Pergunte se alguém precisa de ajuda depois.",
        hint: "Does anyone need help ...",
        answers: ["does anyone need help after this", "does anybody need help after this"],
        tip: "Need help = precisar de ajuda.",
      },
      {
        prompt: "Peça para chegarem no horário amanhã.",
        hint: "Please be on time ...",
        answers: ["please be on time tomorrow", "please be on time tomorrow."],
        tip: "On time tomorrow = no horário amanhã.",
      },
      {
        prompt: "Agradeça e deseje um bom dia.",
        hint: "Thanks everyone ...",
        answers: ["thanks everyone have a good one", "thanks everyone, have a good one"],
        tip: "Have a good one = tenham um bom dia.",
      },
    ],
  },
];
